root@ubt2204s-uefi-amd-diag:/mnt/git/vllm-rocm/benchmarks# python3 benchmark_serving.py --tokenizer /mnt/huggingface.co/facebook_opt-125m/ --dataset /mnt/huggingface.co/ShareGPT_V3/ShareGPT_V3_unfiltered_cleaned_split.json   --model /mnt/git/llama.cpp.docker/models/ --request-rate 40
Namespace(backend='vllm', base_url=None, host='localhost', port=8000, endpoint='/v1/completions', dataset='/mnt/huggingface.co/ShareGPT_V3/ShareGPT_V3_unfiltered_cleaned_split.json', dataset_name='sharegpt', dataset_path=None, model='/mnt/git/llama.cpp.docker/models/', tokenizer='/mnt/huggingface.co/facebook_opt-125m/', best_of=1, use_beam_search=False, num_prompts=1000, sonnet_input_len=550, sonnet_output_len=150, sonnet_prefix_len=200, request_rate=40.0, seed=0, trust_remote_code=False, disable_tqdm=False, save_result=False, metadata=None, result_dir=None)
/mnt/git/vllm-rocm/benchmarks/benchmark_serving.py:590: UserWarning: The '--dataset' argument will be deprecated in the next release. Please use '--dataset-name' and '--dataset-path' in the future runs.
  main(args)
Traffic request rate: 40.0
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:25<00:00, 38.66it/s]
/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.10/dist-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "/mnt/git/vllm-rocm/benchmarks/benchmark_serving.py", line 590, in <module>
    main(args)
  File "/mnt/git/vllm-rocm/benchmarks/benchmark_serving.py", line 406, in main
    benchmark_result = asyncio.run(
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/mnt/git/vllm-rocm/benchmarks/benchmark_serving.py", line 279, in benchmark
    metrics, actual_output_lens = calculate_metrics(
  File "/mnt/git/vllm-rocm/benchmarks/benchmark_serving.py", line 229, in calculate_metrics
    p99_tpot_ms=np.percentile(tpots, 99) * 1000,
  File "/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py", line 4283, in percentile
    return _quantile_unchecked(
  File "/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py", line 4555, in _quantile_unchecked
    return _ureduce(a,
  File "/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py", line 3823, in _ureduce
    r = func(a, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py", line 4722, in _quantile_ureduce_func
    result = _quantile(arr,
  File "/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py", line 4831, in _quantile
    slices_having_nans = np.isnan(arr[-1, ...])
IndexError: index -1 is out of bounds for axis 0 with size 0
